/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BsmImport } from './routes/bsm'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BsmRoute = BsmImport.update({
  id: '/bsm',
  path: '/bsm',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bsm': {
      id: '/bsm'
      path: '/bsm'
      fullPath: '/bsm'
      preLoaderRoute: typeof BsmImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bsm': typeof BsmRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bsm': typeof BsmRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bsm': typeof BsmRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bsm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bsm'
  id: '__root__' | '/' | '/bsm'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BsmRoute: typeof BsmRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BsmRoute: BsmRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bsm"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bsm": {
      "filePath": "bsm.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
